export interface UserInformation {
    deviceId: number|null|undefined,
    email: string|null|undefined,
    firstName:string|null|undefined,
    id:number|null|undefined,
    lastName:string|null|undefined,
    locations:[]|null|undefined,
    nationalIdentificationNumber: null,
    otp: null,
    otpFlag: null,
    profilePic: null,
    reviews: []|null|undefined,
    sellingCategory: []|null|undefined,
    userName: string|null|undefined,
    userRequests: []|null|undefined,
    userType: string|null|undefined,
}
